In [2]:
import numpy as np

In [54]:
a = np.array([1,2,3])
a
a = np.array([[1,2,3],[4,5,6]])
type(a)
a

a.ndim
a.shape
a.size
a.dtype

a = np.array([20,30,40,50])
b = np.arange(4)

a
b
c = a-b
c
b+2


ValueError: operands could not be broadcast together with shapes (2,) (4,) 

In [95]:
b**3
10 * a
a<35
a*b

b = np.arange(12).reshape(3,4)
b.sum()
b.sum(axis=0)
np.argmax(b)
np.argmin(b,axis = 1)
np.exp(b)
np.sqrt(b)
np.mean(b, axis= 0)
np.median(b)

np.std(b)
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [212]:
a = np.arange(10)
a[2:5]
a[:6:2]
a[::-1]
a[::2]

b = np.arange(12).reshape(3,4)
b[2,3]
b[0:2,1]
b[:,1]
b[1:3,:]
b[:,-1]

c = np.array([[ [0,1,2], [10,12,13]], [[100,101,102],[110,112,113]]])
c.shape
c[1,...]
c[...,2]
c[c<2] += 200

a = np.arange(12)
a+=100
i = np.array([1,1,6,7])
a[i]
j = np.array([[3,4],[7,8]])
a[j]

a = np.arange(12).reshape(3,4)
a.ravel()
a.T

b.reshape(4,-1)

a = np.arange(12)
b = a
b is a
b.shape = 3,4
b
a.shape

a = np.arange(12)
c = a.view()
a[3] = 1000
c
a.resize((3,4))
a
c[7] = 123
a
c

In [217]:
b = np.linspace(0,2*np.pi,10)
a = np.sin(b)


print(a)
a = np.random.random((3,3,3))

a

[ 0.00000000e+00  6.42787610e-01  9.84807753e-01  8.66025404e-01
  3.42020143e-01 -3.42020143e-01 -8.66025404e-01 -9.84807753e-01
 -6.42787610e-01 -2.44929360e-16]


array([[[0.76167022, 0.58459342, 0.9619194 ],
        [0.25853491, 0.73883466, 0.85417101],
        [0.96513109, 0.579811  , 0.61316637]],

       [[0.39767362, 0.40322179, 0.76592793],
        [0.63223435, 0.55785014, 0.88892405],
        [0.8898735 , 0.40061423, 0.7129139 ]],

       [[0.39528538, 0.65743726, 0.46549393],
        [0.50139556, 0.41093267, 0.04705856],
        [0.02160881, 0.19598454, 0.01081773]]])

In [170]:
a = np.ones((5,5))
a
a[1:4,1:4] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [187]:
a = np.zeros((5,5))
a[::2,::2] = 1
a[1::2,1::2] = 1
a

array([[1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.]])

In [218]:
a = np.zeros((5,5))
a
for i in range(5):
    a[i,::] = i
print(a)

a = np.random.random(10)
print(a)
a[np.argmax(a)] = 0
print(a)


a = np.random.random((3,3))
a*=10
print(a)
np.sum(a[a>5])

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]
[0.72078096 0.60425559 0.94761713 0.28886007 0.27543546 0.32638808
 0.71807014 0.46220969 0.50600822 0.82641638]
[0.72078096 0.60425559 0.         0.28886007 0.27543546 0.32638808
 0.71807014 0.46220969 0.50600822 0.82641638]
[[6.55490053 1.73600623 5.55377032]
 [6.04192841 0.37135523 4.32459634]
 [6.71993099 9.41043464 8.78457495]]


43.06553982992627